{% set name = "pinocchio" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e49f3d92e303fe109bc8b329513708a03cdb734a90cb7734821ed2978de8d10

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
  host:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - libboost-devel
    - libboost-python-devel
    - python
    - llvm-openmp  # [not win]
    - numpy
    - casadi
    - cppad<=20230000
    - cppadcodegen # [not win and not aarch64 and not ppc64le]
    - mpfr
  run:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - python
    - llvm-openmp  # [not win]
    - {{ pin_compatible('numpy') }}
    - casadi
    - cppad<=20230000
    - cppadcodegen # [not win and not aarch64 and not ppc64le]
    - pycppad
    - mpfr
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}_default${SHLIB_EXT}  # [not win]
  imports:
    - pinocchio

about:
  home: http://github.com/stack-of-tasks/pinocchio
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.LESSER
  summary: A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
  dev_url: https://github.com/stack-of-tasks/pinocchio

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - wolfv
    - ymontmarin
