{% set name = "pinocchio" %}
{% set version = "2.6.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: acfe29de311aa284d829070bf3cb1941166ca3d6fd1331ad63cb094a793273d9

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - boost
    - python
    - llvm-openmp  # [not win]
    - numpy
  run:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - boost
    - python
    - llvm-openmp  # [not win]
    - {{ pin_compatible('numpy') }}
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
  imports:
    - pinocchio

about:
  home: http://github.com/stack-of-tasks/pinocchio
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.LESSER
  summary: A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
  dev_url: https://github.com/stack-of-tasks/pinocchio

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
    - ymontmarin
