{% set name = "pinocchio" %}
{% set version = "2.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 704a0ced354105d13bae294af672bbab6f5b3d696980eef31d9a5b16b2865ed4

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - boost
    - python
  run:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - boost
    - python
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}
  imports:
    - pinocchio

about:
  home: http://github.com/stack-of-tasks/pinocchio
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.LESSER
  summary: A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
  dev_url: https://github.com/stack-of-tasks/pinocchio

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
